---
title: 'Data Visualization & Network Graphs'
subtitle: "ECI 589 SNA and Education: Unit 1 Tutorials & Analysis"
author: "Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
format:
  html:
    toc: true
    toc-depth: 4
theme: 
  light: cosmo
  dark: cyborg
bibliography: lit/references.bib
---

The final week of each unit is designed to provide you some space for gaining proficiency with R and conducting an independent analysis. For students new to R and have not completed ECI 589: Intro to Learning Analytics, you will be required to complete two Posit Primers focused on the basics of R programming and data visualization. For students who have completed ECI 586 or are already comfortable with R basics, you will be required to create a simple "data product" designed to illustrate key insights about about the student and/or teacher reported middle school friendship networks.

## Posit Primers (R Beginners)

For students new to R, the third week of each unit consists of tutorials for working with R packages used import, wrangle, explore, and model data. The primary goal of these tutorials is to support familiarity and fluency with R syntax and key functions for data analysis.

### Assignment

Your assignment this week is to complete the following primers located on [Posit Cloud](https://posit.cloud/learn/primers):

1.  [Visualization Basics](https://posit.cloud/learn/primers/1.1). This tutorial focuses on making plots with R. Plots are one of the most important tools for data science; they are also one of the most fun.
2.  [Programming Basics](https://posit.cloud/learn/primers/1.2). This tutorial demystifies programming with R. Here, you'll learn how to run functions and build objects.

### Assessment

To assess your knowledge and skills, you will complete a brief online quiz worth 6 points. This is an "open book" quiz and you are welcome to refer to the course readings, primers and case study to complete. You will be able to attempt this quiz more than once, though penalties may be assigned for incorrect responses.

## Independent Analysis (ECI 586 Students)

For those who completed ECI 586 or are already comfortable with R, you will be required to conducted an independent analysis and create a simple "data product" designed to illustrate key insights about changes in the collaboration network over time. For the purposes of this assignment, imagine that your audience consists of teachers and school leaders who have limited background in SNA and adapt the following steps accordingly:

### Assignment

1.  **Select.** Select our teacher and student sociograms from above, or create a entirely new sociogram if so motivated, to share with our target audience and that helps answer our research question.

2.  **Polish.** Refine this sociogram and make them visually appealing to help illustrate similarities and differences in classroom friendships reported by teachers and students.

3.  **Narrate.** Write a brief narrative to accompany your visualization and/or table that includes the following:

    -   The question or questions guiding the analysis;

    -   The conclusions you've reached based on our findings;

    -   How your audience might use this information;

    -   How you might revisit or improve upon this analysis in the future.

### Assessment

this assignment, you will demonstrate your ability to formulate a basic research question, wrangle and analyze relational data, and create a simple data product to illustrate key findings. **Your primary goal is to describe a social network both visually and numerically** byapplying the knowledge and skills acquired from the course readings and case study. Grading for this week is fairly lenient and you'll receive 1 point for completing each of the following tasks (6 points  total):

1.  **Identity a data source.** I've included a data folder located the Unit 2 Analysis Project in our [RStudio Cloud ECI 589 Workspace](https://rstudio.cloud/spaces/146919/join?access_code=VgotVV692OpRoxZvrOp9oW8a2EThPX5kHkJ7Vgf8) that contains datasets I've created as well as those from our SNA and Education course text described [here](https://studysites.sagepub.com/carolan/study/resources.htm). You are welcome to chose from those or to identify your own data source related to an area of professional interest.

2.  **Formulate a question.** I recommend keeping this simple and limiting to no more than one or two questions. Your question(s) should be appropriate to your data set and ideally be answered by applying concepts and skills from our course readings and case study. For example, you may be interested in determining measures of centrality for a network and identifying key actors.

3.  **Analyze the data.** I highly recommend creating a new R script in the Unit 2 Analysis project space to use as you work through data wrangling and analysis. Your R script will likely contain code that doesn't make it into your R Markdown presentation or report since you will likely experiment with different approaches and figure out code that works and code that does not.

4.  **Create a data product.** When you feel you've wrangled and analyzed the data to your satisfaction, create an R Markdown file that includes a polished sociogram and/or data table and a narrative highlighting your research question, data source, and key findings and potential implications. Your R Markdown file should include a polished sociogram and/or table, a title and narrative, and all code necessary to read, wrangle, and explore your data.

5.  **Share your findings.** Knit your data product to a desired output format. This may be a simple [HTML](https://bookdown.org/yihui/rmarkdown/html-document.html), [PDF](https://bookdown.org/yihui/rmarkdown/pdf-document.html), or [MS Word](https://bookdown.org/yihui/rmarkdown/word-document.html) file; or something more complex like [HTML5 slides](https://bookdown.org/yihui/rmarkdown/ioslides-presentation.html), a [Tufte-style handout](https://bookdown.org/yihui/rmarkdown/tufte-handouts.html), [dashboard](https://rmarkdown.rstudio.com/flexdashboard/), or [website](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html). Then create a new forum post below to share your analysis. Include in the post your published web link (e.g., via [RPubs](https://rpubs.com/about/getting-started) or [GitHub](https://towardsdatascience.com/how-to-create-a-free-github-pages-website-53743d7524e1)) or attached file (e.g. HTML or PDF) and add a short reflection including one thing you learned and one thing you'd like to explore further.

6.  **Provide some feedback.** Finally, take look at the posted data products and provide some brief (1 paragraph) but constructive feedback to at least two of your peers. Your feedback should include one thing you liked about their data product and why and one suggestion for improvement or extension of the analysis.

### Troubleshooting

If you have any questions about the assignment or run into any technical issues, don't hesitate to email me at [sbkellog\@ncsu.edu(opens in new window)](http://sbkellog@ncsu.edu/) or set up a Zoom meeting at [calendly.com/sbkellogg(opens in new window)](http://calendly.com/sbkellogg).

**If you have questions about the tutorials or exercises, I encourage you to post to the forum below**, especially if others might benefit from the response to question. You are also more than welcome to respond to the questions posted by your peers. However, I do ask that you try work through the exercises independently before reaching out for support.

Finally, you are always welcome to email me directly at [sbkellog\@ncsu.edu(opens in new window)](http://sbkellog@ncsu.edu/) or [set up a meeting(opens in new window)](https://calendly.com/sbkellogg/analytics) with me if you need help. 

## References
