---
title: 'Unit 1 Readings: What is SNA?'
subtitle: "ECI 589 Social Network Analysis and Education"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Readings

This week you'll be required to read chapters 1-2 of Social Network
Analysis and Education [@carolan2014] and find one additional research
article, presentation, or informal study to help address our discussion
questions for the week.

### SNA and Education Part I: Theory and Concepts

1.  [Chapter 1: The Social Network Perspective and Educational Research
    Introduction](https://methods-sagepub-com.prox.lib.ncsu.edu/book/social-network-analysis-and-education/n1.xml)

2.  [Chapter 2: Historical, Theoretical, and Analytical
    Foundations](https://methods-sagepub-com.prox.lib.ncsu.edu/book/social-network-analysis-and-education/n2.xml)

### Self-Selected Study

Use the [NCSU Library](https://www.lib.ncsu.edu/#articles), [Google
Scholar](https://scholar.google.com/) or search engine to locate a
research or practitioner-focused article, presentation, or resource that
applies social network analysis to study a topic of interest. You are
also welcome to select one of the research papers listed in
the [syllabus](https://sbkellogg.github.io/eci-589/) or in our [course
text](https://catalog.lib.ncsu.edu/catalog/NCSU2803782) that may have
peaked your interest and you'd like to follow up on it. Your selection
should address one or more of the discussion topics/questions (see
below) and you're welcome to identify SNA resources outside of the field
of education.

## Discussion

In lieu of the peer interaction and discussion of course materials that
normally take place "in-class", you'll be asked to log in this
week and engage with other members of our learning community through
this discussion forum. With the exception of the [Resource
Review](https://moodle-courses2122.wolfware.ncsu.edu/mod/forum/discuss.php?d=4366)
topic, you are not required to address every guiding question,
particularly if you feel others in the class have thoroughly addressed
the topic or questions.

The primary goal for these discussions is to collectively build our
understanding of this week's topics through back-and-forth dialogue and
avoid a "collective monologue" in which we see 20 variations of
effectively the same post. A secondary goal of these discussion is to
help you brainstorm ideas for independently analysis assignments and/or
your final course project.

## Assessment

Grading for this assignment is fairly lenient, provided that it's clear
from your posts that you've done the required reading. Readings and
discussion for each unit are worth 6 points and judged based on quantity
and quality of your posts.

In term of **quantity** (3 points), you'll be expected to post your
selected resource review add at least 3 replies to the discussion
questions or your peers. These posts should be spread out over the
course of the week and across at least two different days, preferably
not the last two days.  

In terms of **quality** (3 points), your posts over the next week should
provide new or insightful contributions to that question or topic.
There is no requisite for the length of each posting, in fact short
conversational exchanges (1-3 paragraphs) are highly encouraged. I
strongly recommend taking a look at Table 1 of [the productive online
discussion
model](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/287931/mod_forum/post/6203/Gao%2C%20Wang%2C%20Sun%20-%202009%20-%20A%20new%20model%20of%20productive%20online%20discussion%20and%20its%20implications%20for%20research%20and%20instruction.pdf) [@gao2009]
for ways to contribute to the conversation. 

At minimum, your collective posts should also help us interpret or
elaborate on discussion topics, questions, or ideas others have shared
by "making connection to the learning materials" and should reference at
some point each of the required chapters and your self-selected reading
or resource.

## Guiding Questions

To help guide our discussions, we will collectively address a set of
guiding questions provided below. You are also welcome to add your own
topics or questions for the class to discuss.

### Chapter 1: The Social Network Perspective and Educational Research Introduction

1.  Consider a network of which you are a part. Who are the network's
    actors? What ties connect these actors? Are there any groups within
    this network? What relations within this network might be of
    interest to a researcher? Finally, what makes this collection of
    actors a social network?

2.  Draft a research question that would be of interest to educational
    researchers that would require the collection of relational data.
    What relational data would need to be collected? For what reason
    would relational data need to be collected in order to address this
    question?

3.  Using the same question from the previous response, explain the
    analytical level at which these data would need to be collected and
    analyzed.

### Chapter 2: Historical, Theoretical, and Analytical Foundations

Draft a research question for a population you may be interested in
studying, or that would be of interest to educational researchers, and
that would require the collection of relational data. Share your
research question and then answer the following questions:

1.  What relational data would need to be collected? 

2.  For what reason would relational data need to be collected in order
    to address this question?

3.  Explain the analytical level at which these data would need to be
    collected and analyzed.

4.  How does this differ from the ways in which individual or group
    behavior is typically conceptualized and modeled in conventional
    educational research?

### Self-Selected Study: The Four Hallmarks of SNA

#### Required

For your self-selected study, briefly answer the following questions
(Required):

1.  To what degree does the study emphasize one or more of the
    following:

    -   individuals and their actions are viewed as interdependent;

    -   relational ties between individuals are opportunities for
        transmission of resources;

    -   the pattern of relations among individuals---the social
        structure---is an environment that can provide either
        opportunities for or constraints on individual action; and (4)
        social structure as an enduring pattern of relations among
        actors?

2.  At which level are the social network data measured and collected:
    ego, dyad, triad, or complete?

3.  What relations have been measured among actors? Why were these
    relations measured and others excluded?

4.  How and to what degree does the study reflects the four hallmarks of
    social network analysis: 

    1.  emphasis on structuralism based on ties among actors, 

    2.  firmly grounded in empirical data, 

    3.  use of graphical imagery, and 

    4.  mathematically based.

#### Optional

Bonus Questions:

1.  How does the study straddle qualitative and quantitative paradigms?

2.  How does the use of the social network analysis bridge the gap
    between sociological theory and empirical reality?

## References
