---
title: "Unit 6 Final Project: A Network Analysis Case Study"
subtitle: "ECI 589 Social Network Analysis and Education"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

For the end-of-course project, you'll be applying the knowledge and
skills gained throughout this semester to create your "case study"
proposed in [Unit 6 Part
1](https://sbkellogg.github.io/eci-589/unit-6/unit-6-project-planning.html).
Similar to the case studies provided in this course, your case study
should demonstrate your ability to wrangle, analyze, and communicate
findings in response to a research question of interest. Also, similar
to our Unit 1-5 case studies, you'll be expected to use R Markdown to
create a sharable web page (or if preferred, a PDF or Word document),
which includes the code used during each step of your analysis so it can
be reproduced by others.

When you are ready to share your final case study, please click "Add a
new discussion topic" to create a new forum post. In your post, include
a link to your knitted html case study file (or attach your Word or PDF
file), and if you worked in RStudio desktop, also attach or link to your
associated R markdown file use to create you case study. If your data is
sensitive or proprietary and not suitable for including in your post,
please let me know. 

## Grading Criteria

Grading criteria for your final project is guided by the Data-Intensive
Research Workflow from Learning Analytics Goes to School [@krumm2018]
and Social Network Analysis and Education [@carolan2014]. Your final
project is with 24 points, or approximately one-fourth of your overall
grade.

### Prepare (6 points total; 2 points each)

Your case study should demonstrate your ability to formulate clear,
actionable research questions relevant to a targeted audience.
Specifically, your case study should include an **introduction** that:

1.  Clearly describes the **purpose** of your case study, including
    the research question(s) guiding your analyses.

2.  Provides information about the **data sources**, including the
    context in which the data was collected and variables used to
    address your research questions.

3.  Includes a description of the **target audience** that would most
    benefit from your analysis and why.

### Wrangle (6 points total; 2 points each)

Your data project should demonstrate your ability to use R to
manipulate, clean, transform, and/or merge relational data in order to
prepare your network analysis. Specifically, your case study should
clearly describe: 

1.  **Data preprocessing** steps (e.g., renaming variables, filtering,
    dichotomization, recoding values, etc.) taken to clean and prepare
    your text for analysis and why are they necessary.

2.  Any **new variables or features** you created (e.g., degree ,
    reciprocity, etc.) to address your research questions. 

3.  Data **transformations** you made required for the types of analyses
    or packages used (e.g. reshaping, merging, joining, matrix
    conversions, etc.).  

### Analyze (6 points total; 2 points each)

Your data project should demonstrate your ability to use R to apply
network analysis techniques appropriate to your research questions and
data sources. Specifically, your case study shouldclearly include:   

1.  Clear descriptions of the exploratory **techniques and/or
    models** (e.g., level of analysis, community detection, ERGMs, etc.)
    you applied to analyze your data.

2.  Interpretations/meanings of specific **metrics** (e.g., counts,
    means, centrality measures, etc.) that your analysis generated. 

3.  Data **visualizations** that are attractive and easy to interpret,
    and include text or narrative for aiding their Interpretation by
    others.

### Communication (6 points total; 2 points each)

Your case study should demonstrate your ability to clearly and
effectively communicate the most important and most useful findings.
Specifically, your case study should:

1.  Highlights **key finding and insights** in response to your research
    questions. 

2.  Suggests potential **action** that you and/or your target audience
    to better understand and improve the context in which your data
    product is intended to inform.  

3.  Discusses the **limitations** and any ethical/legal
    issues taken into consideration, including acknowledgments any
    reference materials used.

## References
