<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
  <meta charset="utf-8">
  <meta name="generator" content="quarto-0.9.188">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <meta name="author" content="Dr.&nbsp;Shaun Kellogg">
  <meta name="dcterms.date" content="2022-04-05">
  <title>Unit 3: Components, Cliques, &amp; Key Actors</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>

  <script src="unit-3-case-study-key_files/libs/clipboard/clipboard.min.js"></script>
  <script src="unit-3-case-study-key_files/libs/quarto-html/quarto.js"></script>
  <script src="unit-3-case-study-key_files/libs/quarto-html/popper.min.js"></script>
  <script src="unit-3-case-study-key_files/libs/quarto-html/tippy.umd.min.js"></script>
  <script src="unit-3-case-study-key_files/libs/quarto-html/anchor.min.js"></script>
  <link href="unit-3-case-study-key_files/libs/quarto-html/tippy.css" rel="stylesheet">
  <link id="quarto-text-highlighting-styles" href="unit-3-case-study-key_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
  <script src="unit-3-case-study-key_files/libs/bootstrap/bootstrap.min.js"></script>
  <link href="unit-3-case-study-key_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
  <link href="unit-3-case-study-key_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet">
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc">
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#prepare" id="toc-prepare" class="nav-link active" data-scroll-target="#prepare">1. PREPARE</a>
<ul class="collapse">
<li><a href="#a.-review-the-research" id="toc-a.-review-the-research" class="nav-link" data-scroll-target="#a.-review-the-research">1a. Review the Research</a>
<ul class="collapse">
<li><a href="#a-social-network-perspective-in-mooc-eds" id="toc-a-social-network-perspective-in-mooc-eds" class="nav-link" data-scroll-target="#a-social-network-perspective-in-mooc-eds">A Social Network Perspective in MOOC-Eds</a></li>
<li><a href="#research-context" id="toc-research-context" class="nav-link" data-scroll-target="#research-context">Research Context</a></li>
<li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data Sources</a></li>
<li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
</ul></li>
<li><a href="#b.-identify-a-questions" id="toc-b.-identify-a-questions" class="nav-link" data-scroll-target="#b.-identify-a-questions">1b. Identify a Question(s)</a>
<ul class="collapse">
<li><a href="#your-turn-1" id="toc-your-turn-1" class="nav-link" data-scroll-target="#your-turn-1"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
</ul></li>
<li><a href="#c.-load-libraries" id="toc-c.-load-libraries" class="nav-link" data-scroll-target="#c.-load-libraries">1c. Load Libraries</a>
<ul class="collapse">
<li><a href="#your-turn-2" id="toc-your-turn-2" class="nav-link" data-scroll-target="#your-turn-2"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
</ul></li>
</ul></li>
<li><a href="#wrangle" id="toc-wrangle" class="nav-link" data-scroll-target="#wrangle">2. WRANGLE</a>
<ul class="collapse">
<li><a href="#a.-import-data" id="toc-a.-import-data" class="nav-link" data-scroll-target="#a.-import-data">2a. Import Data</a>
<ul class="collapse">
<li><a href="#the-edge-list-format" id="toc-the-edge-list-format" class="nav-link" data-scroll-target="#the-edge-list-format">The Edge-List Format</a></li>
<li><a href="#your-turn-3" id="toc-your-turn-3" class="nav-link" data-scroll-target="#your-turn-3"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
<li><a href="#node-attributes" id="toc-node-attributes" class="nav-link" data-scroll-target="#node-attributes">Node Attributes</a></li>
<li><a href="#your-turn-4" id="toc-your-turn-4" class="nav-link" data-scroll-target="#your-turn-4">👉 Your Turn <strong>⤵</strong></a></li>
</ul></li>
<li><a href="#b.-create-network-object" id="toc-b.-create-network-object" class="nav-link" data-scroll-target="#b.-create-network-object">2b. Create Network Object</a>
<ul class="collapse">
<li><a href="#convert-to-graph-object" id="toc-convert-to-graph-object" class="nav-link" data-scroll-target="#convert-to-graph-object">Convert to Graph Object</a></li>
<li><a href="#your-turn-5" id="toc-your-turn-5" class="nav-link" data-scroll-target="#your-turn-5"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
</ul></li>
</ul></li>
<li><a href="#explore" id="toc-explore" class="nav-link" data-scroll-target="#explore">3. EXPLORE</a>
<ul class="collapse">
<li><a href="#a.-analyze-groups-components-cliques" id="toc-a.-analyze-groups-components-cliques" class="nav-link" data-scroll-target="#a.-analyze-groups-components-cliques">3a. Analyze Groups: Components &amp; Cliques</a>
<ul class="collapse">
<li><a href="#components" id="toc-components" class="nav-link" data-scroll-target="#components">Components</a></li>
<li><a href="#cliques" id="toc-cliques" class="nav-link" data-scroll-target="#cliques">Cliques</a></li>
<li><a href="#your-turn-6" id="toc-your-turn-6" class="nav-link" data-scroll-target="#your-turn-6"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
</ul></li>
<li><a href="#b.-egocentric-analysis-size-centrality" id="toc-b.-egocentric-analysis-size-centrality" class="nav-link" data-scroll-target="#b.-egocentric-analysis-size-centrality">3b. Egocentric Analysis: Size &amp; Centrality</a>
<ul class="collapse">
<li><a href="#size" id="toc-size" class="nav-link" data-scroll-target="#size">Size</a></li>
<li><a href="#centrality" id="toc-centrality" class="nav-link" data-scroll-target="#centrality">Centrality</a></li>
<li><a href="#your-turn-7" id="toc-your-turn-7" class="nav-link" data-scroll-target="#your-turn-7"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
</ul></li>
</ul></li>
<li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">4. MODEL</a>
<ul class="collapse">
<li><a href="#your-turn-8" id="toc-your-turn-8" class="nav-link" data-scroll-target="#your-turn-8"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
</ul></li>
<li><a href="#communicate" id="toc-communicate" class="nav-link" data-scroll-target="#communicate">5. COMMUNICATE</a>
<ul class="collapse">
<li><a href="#your-turn-9" id="toc-your-turn-9" class="nav-link" data-scroll-target="#your-turn-9"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
<li><a href="#data-visualization-or-table" id="toc-data-visualization-or-table" class="nav-link" data-scroll-target="#data-visualization-or-table">Data Visualization or Table</a></li>
<li><a href="#narrative" id="toc-narrative" class="nav-link" data-scroll-target="#narrative">Narrative</a></li>
<li><a href="#knit-check" id="toc-knit-check" class="nav-link" data-scroll-target="#knit-check">🧶 Knit &amp; Check ✅</a></li>
<li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
</ul></li>
</ul>
</nav>
</div>
<main class="content" id="quarto-document-content">
<header id="title-block-header" class="quarto-title-block default">




<div class="quarto-title"><h1 class="title display-7">Unit 3: Components, Cliques, &amp; Key Actors</h1><p class="subtitle lead">ECI 589 Social Network Analysis and Education</p></div><div class="quarto-title-meta"><div><div class="quarto-title-meta-heading">Author</div><div class="quarto-title-meta-contents"><div class="quarto-title-authors"><div><div>
<p>Dr.&nbsp;Shaun Kellogg</p>
</div></div></div></div></div><div><div class="quarto-title-meta-heading">Published</div><div class="quarto-title-meta-contents"><p class="date">April 5, 2022</p></div></div></div></header>

<section id="prepare" class="level2">
<h2 class="anchored" data-anchor-id="prepare">1. PREPARE</h2>
<p>The primary goal in this case study is to examine the use of different algorithms to analyze a network’s groups and individual actors. Using an open educational dataset prepared by Kellogg and Edelman <span class="citation" data-cites="kellogg2015massively">Kellogg and Edelmann (<a href="#ref-kellogg2015massively" role="doc-biblioref">2015</a>)</span>, we’ll explore both “top-down” and “bottom-up” approaches to identifying groups within our network, as well as node-level measures of centrality to identify key actors. Specifically, the Unit 3 case study will cover the following topics:</p>
<ol type="1">
<li><p><strong>Prepare</strong>: Prior to analysis, we’ll take a look at the context from which our data came, formulate simple research questions to guide our analysis, and load some by now familiar R packages for network analysis.</p></li>
<li><p><strong>Wrangle</strong>: Wrangling data entails the work of manipulating, cleaning, transforming, and merging data. In section 2 we focus on importing network data, and converting edge and node lists into a network object that can be analyzed and graphed.</p></li>
<li><p><strong>Explore</strong>: In section 3, we look at components and cliques within our network, and learn how to add add summarize important node-level measures of centrality.</p></li>
<li><p><strong>Model</strong>: While we won’t dig into approaches for modeling network data until Unit 4, we will take a quick look at some approaches used in the research article guiding this study.</p></li>
<li><p><strong>Communicate</strong>: Finally, you’ll prepare a simple “data product” consisting of a data visualization and/or table that highlights some key findings from our analysis.</p></li>
</ol>
<section id="a.-review-the-research" class="level3">
<h3 class="anchored" data-anchor-id="a.-review-the-research">1a. Review the Research</h3>
<p>In <a href="https://methods.sagepub.com/book/social-network-analysis-and-education">Social Network Analysis and Education: Theory, Methods &amp; Applications</a>, Carolan (2013) notes that:</p>
<blockquote class="blockquote">
<p>the <strong>social network perspective</strong> is one concerned with the structure of relations and the implication this structure has on individual or group behavior and attitudes</p>
</blockquote>
<p>More specifically, Carolan cites the following four features used by Freeman (2004) to define the social network perspective:</p>
<ol type="1">
<li><p>Social network analysis is <strong>motivated by a relational intuition</strong> based on ties connecting social actors.</p></li>
<li><p>It is firmly <strong>grounded in systematic empirical data</strong>.</p></li>
<li><p>It <strong>makes</strong> <strong>use of graphic imagery</strong> to represent actors and their relations with one another.</p></li>
<li><p>It <strong>relies</strong> <strong>on</strong> <strong>mathematical and/or computational models</strong> to succinctly represent the complexity of social life.</p></li>
</ol>
<p>For Unit 3, our case study is guided by previous research and evaluation work conducted by the Friday Institute for Educational Innovation as part of the Massively Open Online Courses for Educators (MOOC-Ed) initiative. The study introduced next and our hands-on analysis with R will help to illustrate these four defining features of the social network perspective.</p>
<section id="a-social-network-perspective-in-mooc-eds" class="level4">
<h4 class="anchored" data-anchor-id="a-social-network-perspective-in-mooc-eds">A Social Network Perspective in MOOC-Eds</h4>
<p><img src="img/irrodl-article.png" class="img-fluid" style="width:50.0%"></p>
<p>Kellogg, S., Booth, S., &amp; Oliver, K. (2014). <a href="https://github.com/sbkellogg/eci-589/blob/main/unit-1/lit/sna_mooc_irrodl_bjet_articles.pdf">A social network perspective on peer supported learning in MOOCs for educators</a>.&nbsp;<em>International Review of Research in Open and Distributed Learning</em>,&nbsp;<em>15</em>(5), 263-289.</p>
</section>
<section id="research-context" class="level4">
<h4 class="anchored" data-anchor-id="research-context">Research Context</h4>
<p>In the spring of 2013, The Friday Institute launched the MOOC-Ed Initiative to explore the potential of delivering personalized, high-quality professional development to educators at scale (Kleiman et al., 2013). In collaboration with the Alliance for Excellent Education, the Friday Institute launched this initiative with a 6-week pilot course called Planning for the Digital Learning Transition in K-12 Schools (DLT 1), which was offered again in September 2013 (DLT 2). This course was designed to help school and district leaders plan and implement K-12 digital learning initiatives.</p>
<p>Academics, as well as pundits from traditional and new media, have raised a number of concerns about MOOCs, including the lack of instructional and social supports. Among the core design principles of MOOC-Eds are collaboration and peer-supported learning. It is an assumption of this study that challenges arising form this problem of scale can be addressed by leveraging these massive numbers to develop robust online learning communities.</p>
<p>This mixed-methods case study used both SNA and qualitative methods to better understand peer support in MOOC-Eds through an examination of the characteristics, mechanisms, and outcomes of peer networks. Findings from this study demonstrate that even with technology as basic as a discussion forum, MOOCs can be leveraged to foster these networks and facilitate peer-supported learning. Although this study was limited to two unique cases along the wide spectrum of MOOCs, the methods applied provide other researchers with an approach for better understanding the dynamic process of peer supported learning in MOOCs.</p>
</section>
<section id="data-sources" class="level4">
<h4 class="anchored" data-anchor-id="data-sources">Data Sources</h4>
<p><strong>MOOC-Ed registration form.</strong> All participants completed a registration form for each MOOC-Ed course. The registration form consists of self-reported demographic data, including information related to their professional role and work setting, years of experience in education, and personal learning goals.</p>
<p><strong>MOOC-Ed discussion forums.</strong> All peer interaction, including peer discussion, feedback, and reactions (e.g., likes), take place within the forum area of MOOC-Eds, which are powered by Vanilla Forums. Because of the specific focus on peer supported learning, postings to or from course facilitators and staff were removed from the data set. Finally, analyses described below exclude more passive forms of interactions (i.e., read and reaction logs), and include only postings among peers.</p>
<p>For our Unit 3 case study, we’ll take a look at data from the original Digital Learning Transition in K-12 Schools (DLT 1) that was not included in this study. <strong>For your independent analysis next week, you may want to consider working with the DLT 2 data to see if you can replicate some of the findings from this paper!</strong></p>
<p><strong>Note</strong>: In the data we’re using, instructors have not yet been removed and only direct replies to forum posts have been included, though “weaker” ties like reactions with emoticons and even views of posts were captured in this study.</p>
</section>
<section id="your-turn" class="level4">
<h4 class="anchored" data-anchor-id="your-turn"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Take a quick look at the <em>Description of the Dataset</em> section from the <a href="https://github.com/sbkellogg/eci-589/blob/main/unit-1/lit/bjet_12312_Rev.pdf">Massively Open Online Course for Educators (MOOC-Ed) network dataset</a> BJET article and the accompanying data sets stored on <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZZH3UB">Harvard Dataverse</a> that we’ll be using for this case study.</p>
<p>In the space below, type a brief response to the following questions:</p>
<ol type="1">
<li><p>What were some of the steps necessary to construct the edges in this dataset?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>What “node attributes” are included in this dataset? How might they be used for analysis?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>What else do you notice/wonder about this dataset?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
</section>
</section>
<section id="b.-identify-a-questions" class="level3">
<h3 class="anchored" data-anchor-id="b.-identify-a-questions">1b. Identify a Question(s)</h3>
<p>A Social Network Perspective on Peer Supported Learning was framed by three primary research questions related to peer supported learning:</p>
<ol type="1">
<li><p>What are the patterns of peer interaction and the structure of peer networks that emerge over the course of a MOOC-Ed?</p></li>
<li><p>To what extent do participant and network attributes (e.g., homophily, reciprocity, transitivity) account for the structure of these networks?</p></li>
<li><p>To what extent do these networks result in the co-construction of new knowledge?</p></li>
</ol>
<p>For Unit 3, our exploratory analysis is guided by RQ1 from the original study with an additional emphasis on examining groups and key actors that emerge in the discussion forums for the first and second implementation of the Digital Learning Transition MOOC-Eds. Specifically, for our case we’re interested in the following questions examining groups and key actors:</p>
<ol type="1">
<li>How many network components and cliques are in first and second iteration of DLT 1 and DLT 2?</li>
<li>Which actors are central to each of these networks and what attributes, if any, do they share?</li>
</ol>
<section id="your-turn-1" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-1"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Based on what you know about networks and the context so far, what other research question(s) might ask we ask in this context that a social network perspective might be able to answer?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul>
</section>
</section>
<section id="c.-load-libraries" class="level3">
<h3 class="anchored" data-anchor-id="c.-load-libraries">1c. Load Libraries</h3>
<p>As highlighted in <a href="https://datascienceineducation.com/c06.html#c06p">Chapter 6 of Data Science in Education Using R</a> (DSIEUR):</p>
<blockquote class="blockquote">
<p>Packages are shareable collections of R code that can contain functions, data, and/or documentation. Packages increase the functionality of R by providing access to additional functions to suit a variety of needs.</p>
</blockquote>
<p>You should see installed some familiar tidytext packages from our <a href="https://sbkellogg.github.io/eci-589/unit-0/unit-0-walkthrough.html">Getting Started Walkthrough</a> like {dplyr} and {readr} which we’ll be using again shortly. You should also see an important package call {igraph} that we will rely on heavily for our network analyses in this course.</p>
<p>If you are working in RStudio Desktop, or notice that the packages have not been installed and/or loaded, run the following <code>install.packages()</code> function code to install the {tidyverse} and {igraph} packages:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"igraph"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="your-turn-2" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-2"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Use the <code>library()</code> function and the code chunk below and load the following packages:</p>
<ul>
<li>tidyverse</li>
<li>igraph</li>
<li>tidygraph</li>
<li>ggraph</li>
<li>skmir</li>
<li>janitor</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOUR CODE HERE</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidygraph)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>RStudio Tip:</strong> You can always check to see which packages have already been installed and loaded into RStudio Cloud by looking at the the Files, Plots, &amp; Packages Pane in the lower right hand corner of RStudio as shown in the following screenshot:</p>
<p><img src="img/packages-pane.png" class="img-fluid" style="width:90.0%"></p>
<hr>
</section>
</section>
</section>
<section id="wrangle" class="level2">
<h2 class="anchored" data-anchor-id="wrangle">2. WRANGLE</h2>
<p>In general, data wrangling involves some combination of cleaning, reshaping, transforming, and merging data <span class="citation" data-cites="wickham2016r">(<a href="#ref-wickham2016r" role="doc-biblioref">Wickham and Grolemund 2016</a>)</span>. The importance of data wrangling is difficult to overstate, as it involves the initial steps of going from the raw data to a dataset that can be explored and modeled <span class="citation" data-cites="krumm2018">(<a href="#ref-krumm2018" role="doc-biblioref">Krumm, Means, and Bienkowski 2018</a>)</span>.</p>
<p>For our data wrangling this week, we’re keeping it simple since working with network data is a bit of a departure from our working with rectangular data frames. Our primary goals for Section 2 are learning how to:</p>
<ol type="a">
<li><p><strong>Import Lists</strong>. An obvious and also important first step, we need to “read” our data into R and learn about formatting for edge-lists and node attribute files.</p></li>
<li><p><strong>Create a Graph Object</strong>. Before performing network analyses, we’ll need to convert our data frames into a graph object for working with relational data.</p></li>
</ol>
<section id="a.-import-data" class="level3">
<h3 class="anchored" data-anchor-id="a.-import-data">2a. Import Data</h3>
<section id="the-edge-list-format" class="level4">
<h4 class="anchored" data-anchor-id="the-edge-list-format">The Edge-List Format</h4>
<p>To get started, we need to import, or “read”, our data into R. The function used to import your data will depend on the file format of the data you are trying to import, but R is pretty adept at working with many files types.</p>
<p>Take a look in the <code>/data</code> folder in your Files pane. You should see the following .csv files:</p>
<ul>
<li><p><code>dlt1-edges.csv</code></p></li>
<li><p><code>dlt1-nodes.csv</code></p></li>
</ul>
<p>The first file <code>dlt1-edges.csv</code> is an edge-list that contains information about each tie, or relation between two actors in a network. In this context, a “tie” is a reply by one participant in the discussion forum to the post of another participant – or in some cases to their own post! These ties between a single actor are called “self-loops” and as we’ll see later, {tidygraph} has a special function to remove these self loops from a sociogram, or network visualization.</p>
<p>The edge-list format is slightly different than other formats you have likely worked with before in that the values in the first two columns each row represent a dyad, or tie between two nodes in a network. An edge-list can also contain other information regarding the strength, duration, or frequency of the relationship, sometime called “weight”, in addition to other “edge attributes.”</p>
<p>In addition to our <code>Sender</code> and <code>Reciever</code> dyad pairs, our DLT 1 dataset contains the following edge attributes:</p>
<ul>
<li><p><code>Sender</code> = Unique identifier of author of comment</p></li>
<li><p><code>Receiver</code> = Unique identifier of identified recipient of comment</p></li>
<li><p><code>Timestamp</code> = Time post or reply was posted</p></li>
<li><p><code>Parent</code> = Primary category or topic of thread</p></li>
<li><p><code>Category</code> = Subcategory or subtopic of thread</p></li>
<li><p><code>Thread_id</code> = Unique identifier of a thread</p></li>
<li><p><code>Comment_id</code> = Unique identifier of a comment\</p></li>
</ul>
<p>Let’s use the <code>read_csv()</code> function from the {readr} and {janitor} packages introduced in previous units to read in our edge-list and clean up the variables names:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dlt1_ties <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/dlt1-edges.csv"</span>, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">Sender =</span> <span class="fu">col_character</span>(), </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">Receiver =</span> <span class="fu">col_character</span>(), </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                                       <span class="st">`</span><span class="at">Category Text</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                                       <span class="st">`</span><span class="at">Comment ID</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_character</span>(), </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                                       <span class="st">`</span><span class="at">Discussion ID</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_character</span>())) <span class="sc">|&gt;</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>dlt1_ties</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 2,529 × 9
   sender receiver timestamp   discussion_title discussion_cate… parent_category
   &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;       &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;          
 1 360    444      4/4/13 16:… Most important … Group N          Units 1-3 Disc…
 2 356    444      4/4/13 18:… Most important … Group D-L        Units 1-3 Disc…
 3 356    444      4/4/13 18:… DLT Resources—C… Group D-L        Units 1-3 Disc…
 4 344    444      4/4/13 18:… Most important … Group O-T        Units 1-3 Disc…
 5 392    444      4/4/13 19:… Most important … Group U-Z        Units 1-3 Disc…
 6 219    444      4/4/13 19:… Most important … Group M          Units 1-3 Disc…
 7 318    444      4/4/13 19:… Most important … Group M          Units 1-3 Disc…
 8 4      444      4/4/13 19:… Most important … Group N          Units 1-3 Disc…
 9 355    356      4/4/13 20:… DLT Resources—C… Group D-L        Units 1-3 Disc…
10 355    444      4/4/13 20:… Most important … Group D-L        Units 1-3 Disc…
# … with 2,519 more rows, and 3 more variables: discussion_identifier &lt;chr&gt;,
#   comment_id &lt;chr&gt;, discussion_id &lt;chr&gt;</code></pre>
</div>
</div>
<p>Note the addition of the <code>col_types =</code> argument for changing the column types to character strings since the numbers for those particular columns indicate actors (<code>Sender</code> and <code>Reciever</code>) and attributes (<code>Comment_ID</code> and <code>Discussion_Id</code>). We also skipped the <code>Category Text</code> since this was left blank for deidentification purposes.</p>
</section>
<section id="your-turn-3" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-3"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Consider the example pictured below of a discussion thread from the Planning for the Digital Learning Transition in K-12 Schools (DLT 1) where our data orginated. This thread was initiated by participant I, so the comments by J and N are considered to be directed at I. The comment of B, however, is a direct response to the comment by N as signaled by the use of the quote-feature as well as the explicit mentioning of N’s name within B’s comment.</p>
<p><img src="img/discussion-thread.png" class="img-fluid"></p>
<p>Now answer the following questions as they relate to the DLT 1 edge-list we just read into R.</p>
<ol type="1">
<li><p>Which actors in this thread are the <code>Sender</code> and the <code>Reciever</code>? Which actor is both?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>How many dyads are in this thread? Which pairs of actors are dyads?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
<p><strong>Sidebar:</strong> Unfortunately, these types of nuances in discussion forum data as illustrated by this simple example are rarely captured through automated approaches to constructing networks. Fortunately, the dataset you are working with was carefully reviewed to try and capture more accurately the intended recipients of each reply.</p>
</section>
<section id="node-attributes" class="level4">
<h4 class="anchored" data-anchor-id="node-attributes">Node Attributes</h4>
<p>The second file we’ll be using contains all the nodes or actors (i.e., participants who posted to the discussion forum) as well as some of their attributes such as gender and years of experience in education.</p>
<p>Carolan (2013) notes that most social network analyses include variables that describe attributes of actors, ones that are either categorical (e.g., sex, race, etc.) or continuous in nature (e.g., test scores, number of times absent, etc.). These attributes that can be incorporated into a network graph or model, making it more informative and can aid in testing or generating hypotheses.</p>
<p>These attribute variables are typically included in a rectangular array, or dataframe, that mimics the actor-by-attribute that is the dominant convention in social science, i.e.&nbsp;rows represent cases, columns represent variables, and cells consist of values on those variables.</p>
<p>As an aside, Carolan also refers to this historical preference by researchers for “actor-by-attribute” data, in the absence of relational data in which the actor has been removed their social context, as the “sociological meatgrinder” in action. Specifically, this historical approach assumes that the actor does not interact with anyone else in the study and that outcomes are solely dependent of the characteristics of the individual.</p>
</section>
<section id="your-turn-4" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-4">👉 Your Turn <strong>⤵</strong></h4>
<p>Use the code chunk below to import the <code>dlt1-nodes.csv</code> attribute file and be sure to set the following variables as character data types: <code>UID</code>, <code>Facilitator</code>, <code>expert</code>, <code>connect</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOUR CODE HERE</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dlt1_actors <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/dlt1-nodes.csv"</span>, </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">UID =</span> <span class="fu">col_character</span>(), </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">Facilitator =</span> <span class="fu">col_character</span>(), </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">expert =</span> <span class="fu">col_character</span>(), </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">connect =</span> <span class="fu">col_character</span>())) <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now use the code chunk below to inspect the data you imported and complete the matching exercise that follows:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#YOUR CODE HERE</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>dlt1_actors</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 445 × 13
   uid   facilitator role1 experience experience2 grades location region country
   &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  
 1 1     0           libm…          1 6 to 10     secon… VA       South  US     
 2 2     0           clas…          1 6 to 10     secon… FL       South  US     
 3 3     0           dist…          2 11 to 20    gener… PA       North… US     
 4 4     0           clas…          2 11 to 20    middle NC       South  US     
 5 5     0           othe…          3 20+         gener… AL       South  US     
 6 6     0           clas…          1 4 to 5      gener… AL       South  US     
 7 7     0           inst…          2 11 to 20    gener… SD       Midwe… US     
 8 8     0           spec…          1 6 to 10     secon… BE       Inter… BE     
 9 9     0           clas…          1 6 to 10     middle NC       South  US     
10 10    0           scho…          2 11 to 20    middle NC       South  US     
# … with 435 more rows, and 4 more variables: group &lt;chr&gt;, gender &lt;chr&gt;,
#   expert &lt;chr&gt;, connect &lt;chr&gt;</code></pre>
</div>
</div>
<p>Match up the attributes included in the node file with the following codebook descriptors. The first one has been done as an example.</p>
<ul>
<li><code>Facilitator</code> = Identification of course facilitator (1 = instructor)</li>
<li>Dummy variable for whether participants listed networking and collaboration with others as one of their course goals on the registration form</li>
<li>Identifier of “expert panelists” invited to course to share experience through recorded Q&amp;A</li>
<li>Identification of course facilitator (1 <strong>=</strong> instructor)</li>
<li>Professional role (eg, teacher, librarian, administrator)</li>
<li>Years of experience as an educator</li>
<li>Works with elementary, middle, and/or high school students</li>
<li>Initial assignment of discussion group</li>
</ul>
<p><strong>RStudio Tip:</strong> Importing data and dealing with data types can be a bit tricky, especially for beginners. Fortunately, RStudio has an “Import Dataset” feature in the Environment Pane that can help you use the {readr} package and associated functions to greatly facilitate this process.</p>
<p><img src="img/import-data.png" class="img-fluid"></p>
</section>
</section>
<section id="b.-create-network-object" class="level3">
<h3 class="anchored" data-anchor-id="b.-create-network-object">2b. Create Network Object</h3>
<p>As demonstrated in our previous case study, we first need to convert the data frames that we imported into an network object before we can begin using many of the functions from our network packages for summarizing and visualizing our DLT 1 network.</p>
<section id="convert-to-graph-object" class="level4">
<h4 class="anchored" data-anchor-id="convert-to-graph-object">Convert to Graph Object</h4>
<p>To do that, we will use the <code>tbl_graph()</code> function from the {tidygraph} package. Note that I included the <code>eval=FALSE</code> argument in the code block below to prevent this code from running when we knit our final document. Otherwise it will produce an error since we can’t include help documentation in our knitted HTML file.</p>
<p>Run the following code to take a look at the help documentation for this function:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>?tbl_graph</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You probably saw that this particular function takes the following three arguments, two of which are data frames:</p>
<ul>
<li><p><strong><code>edges =</code></strong> A <code>data.frame</code> containing information about the edges in the graph. The terminal nodes of each edge must either be encoded in a <code>to</code> and <code>from</code> column, or be in the two first columns.</p></li>
<li><p><strong><code>nodes =</code></strong>&nbsp;a node list that starts with a column of node IDs. Any following columns are interpreted as node attributes.</p></li>
<li><p><strong><code>node_key =</code></strong> The name of the column in <code>nodes</code> that character represented <code>to</code> and <code>from</code> columns should be matched against.</p></li>
<li><p><strong><code>directed =</code></strong> determines whether or not to create a directed graph.</p></li>
</ul>
<p>Run the following code to specify our <code>ties</code> data frame as the edges of our network, our <code>actors</code> data frame for the vertices of our network and their attributes, and indicate that this is indeed a directed network.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="ot">&lt;-</span> <span class="fu">tbl_graph</span>(<span class="at">edges =</span> dlt1_ties,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">nodes =</span> dlt1_actors,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">node_key =</span> <span class="st">"uid"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">directed =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="your-turn-5" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-5"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Take a look at the output for our <code>dlt1_network</code> and answer the questions that follow:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#YOUR CODE HERE</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dlt1_network</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tbl_graph: 445 nodes and 2529 edges
#
# A directed multigraph with 4 components
#
# Node Data: 445 × 13 (active)
  uid   facilitator role1 experience experience2 grades location region country
  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  
1 1     0           libm…          1 6 to 10     secon… VA       South  US     
2 2     0           clas…          1 6 to 10     secon… FL       South  US     
3 3     0           dist…          2 11 to 20    gener… PA       North… US     
4 4     0           clas…          2 11 to 20    middle NC       South  US     
5 5     0           othe…          3 20+         gener… AL       South  US     
6 6     0           clas…          1 4 to 5      gener… AL       South  US     
# … with 439 more rows, and 4 more variables: group &lt;chr&gt;, gender &lt;chr&gt;,
#   expert &lt;chr&gt;, connect &lt;chr&gt;
#
# Edge Data: 2,529 × 9
   from    to timestamp discussion_title discussion_cate… parent_category
  &lt;int&gt; &lt;int&gt; &lt;chr&gt;     &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;          
1   360   444 4/4/13 1… Most important … Group N          Units 1-3 Disc…
2   356   444 4/4/13 1… Most important … Group D-L        Units 1-3 Disc…
3   356   444 4/4/13 1… DLT Resources—C… Group D-L        Units 1-3 Disc…
# … with 2,526 more rows, and 3 more variables: discussion_identifier &lt;chr&gt;,
#   comment_id &lt;chr&gt;, discussion_id &lt;chr&gt;</code></pre>
</div>
</div>
<ol type="1">
<li><p>How does the number of node and edges in our DLT 1 network compare to the totals reported for the DLT 2, the second iteration of this MOOC-Ed, reported on in our <a href="https://github.com/sbkellogg/eci-589/blob/main/unit-1/lit/sna_mooc_irrodl_bjet_articles.pdf">guiding study</a>?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>Do the number of nodes and edges are in our network match the number of observations in our node and edge list .csv files? <strong>Hint:</strong> Check the Environment pane.</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>Our output notes that our network is a directed multigraph, indicating that some dyads may have multiple edges. Why might that be?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
<hr>
</section>
</section>
</section>
<section id="explore" class="level2">
<h2 class="anchored" data-anchor-id="explore">3. EXPLORE</h2>
<p>As noted in the previous units, exploratory data analysis involves the processes of describing your network through mathematical measures and/or data visualization. In Section 3, we learn some new functions for identifying groups and subgroups and creating node-level measures to identify central actors in our network. Specifically, in this section we’ll focus on:</p>
<ol type="a">
<li><p><strong>Group Analysis</strong>. We take a look at both a top-down and bottom-up approach to identifying groups within a network by examining the weak and strong components in our network as well as existing cliques.</p></li>
<li><p><strong>Egocentric Analysis</strong>. We also examine the size of an ego’s “local neighborhood” as well as key centrality measures for each node such as degree, closeness, and betweenness.</p></li>
</ol>
<section id="a.-analyze-groups-components-cliques" class="level3">
<h3 class="anchored" data-anchor-id="a.-analyze-groups-components-cliques">3a. Analyze Groups: Components &amp; Cliques</h3>
<section id="components" class="level4">
<h4 class="anchored" data-anchor-id="components">Components</h4>
<p>As noted in Social Network Analysis and Education <span class="citation" data-cites="carolan2014">(<a href="#ref-carolan2014" role="doc-biblioref">Carolan 2014</a>)</span>, one of the most basic ways in which network researchers first characterize a network’s substructure is to identify its components.</p>
<blockquote class="blockquote">
<p>A <strong>component</strong> is a connected subgraph in which there is a path between all pairs of nodes.</p>
</blockquote>
<p>Recall from our output above that our “multigraph” had 4 components. Let’s take a quick look at our network and see if we can spot the 4 components:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autograph</span>(dlt1_network)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="unit-3-case-study-key_files/figure-html/autograph-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As you can see, three of our components are isolates in our network, meaning they have no connections, or forum replies to or from, anyone else in the network. That is, they posted to a discussion forum and never received a reply, or replied to the posts of others.</p>
<p>Directed graphs, such as the DLT 1 network, have two different kinds of components: weak and strong. A weak component, like ours above, ignores the direction of a tie; strong components do not. Rather,</p>
<blockquote class="blockquote">
<p><strong>Strong components</strong> consist of nodes that are connected to one another via both directions along the path that connects them.</p>
</blockquote>
<p>This concept of a component is simple and very useful, especially when analyzing a large network with many components. Often, researchers extract each component and analyze it as a separate network. We won’t be doing that here, but it would be very reasonable to remove the isolates from our network prior to further analysis.</p>
<p>The {igraph} package has a simple function for identifying the number of components in a network, the size of each component, and which actors belong to each. Let’s first take a quick look at the summaries for “weak” components in our network:</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">components</span>(dlt1_network, <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"weak"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>$membership
  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [75] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[112] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[149] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[186] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[223] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[260] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[297] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[334] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[371] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
[408] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 3 4 1
[445] 1

$csize
[1] 442   1   1   1

$no
[1] 4</code></pre>
</div>
</div>
<p>While not incredibly intuitive to interpret, the output indicates that there are 4 components as we discovered above, 1 component has 442 members and three (our isolates) have only 1 member.</p>
<p>One issue with this output that the {tidygraph} package is great at solving is identifying and saving as a new variable who belongs to which component. We can sort of see from above that the first 400+ actors in our network belong to component 1, while the three isolates towards the end belong to components 2, 3, and 4 respectively; and the last two nodes in our network also belong to component 1.</p>
<p>How do you think you might find the “strong” components in our network using the <code>component()</code> function? Use the following code chunk to test out your theory:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOUR CODE HERE</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">components</span>(dlt1_network, <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"strong"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>$membership
  [1] 194 194 194 194 194 194 194 194 194 194 194 194 194 194 194 194 194 193
 [19] 194 194 203 194 209 194 194 194 194 192 194 194 191 194 194 194 194 194
 [37] 194 194 194 190 194 194 194 194 194 194 189 194 194 194 194 194 194 194
 [55] 188 194 194 194 194 194 194 194 194 194 194 194 194 194 194 194 194 194
 [73] 187 194 194 194 194 194 186 194 194 194 194 208 194 185 194 194 184 194
 [91] 194 194 183 194 181 180 178 194 194 194 194 177 194 194 194 194 194 176
[109] 194 194 175 194 194 194 194 194 194 194 194 174 194 194 169 168 167 166
[127] 165 194 194 164 194 194 194 163 162 194 194 194 161 159 194 194 158 194
[145] 173 182 157 156 155 172 171 194 206 194 194 194 194 194 194 154 194 194
[163] 194 153 194 152 194 151 150 194 149 194 194 148 202 194 194 194 147 146
[181] 194 201 194 194 194 145 195 194 198 194 194 194 194 194 194 144 194 194
[199] 194 194 194 143 194 142 194 194 194 194 194 141 194 194 140 139 138 194
[217] 194 194 194 137 194 194 194 136 135 194 194 134 133 131 130 129 128 204
[235] 194 127 126 125 160 124 123 122 194 121 119 194 194 194 194 194 194 194
[253] 194 194 118 194 194 179 117 115 116 194 120 114 194 194 113 194 112 194
[271] 194 194 199 111 194 194 194 110 194 109 194 108 106 107 194 200 194 105
[289] 104 103 102 194 194 101 194 100  99  98  97 194 194 194 194  96 194 197
[307] 194 207  95 194  94  93  92  91  90  89 194 194 194  88 194 194 194 205
[325] 194  87  86  85 194 170 194  84  83 196 194 194 194 194 194 194 194 194
[343] 194 132 194 194 194  82  81 194 194  80  79  78 194 194  77 194  76  75
[361] 194  74  73  72  71  70  69  68  67  66  65  64  63  62  61  60  59  58
[379]  57  56  55  54  53  52  51  50  49  48  47  46  45  44  43  42  41  40
[397]  39  38  37  36  35  34  33  32  31  30  29  28  27  26  25  24 194  23
[415]  22  21  20  19  18  17  16 194  15  14  13  12  11  10   9   8   7 194
[433] 194 194   6   5 194 194 194   4   3   2   1 194 194

$csize
  [1]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
 [19]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
 [37]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
 [55]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
 [73]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
 [91]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
[109]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
[127]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
[145]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
[163]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
[181]   1   1   1   1   1   1   1   1   1   1   1   1   1 237   1   1   1   1
[199]   1   1   1   1   1   1   1   1   1   1   1

$no
[1] 209</code></pre>
</div>
</div>
<p>Wow! If your code was correct, you’ll see that we have a whopping 209 distinct components!</p>
<p>As demonstrated in the previous case study, the {tidygraph} package has a very useful <code>activate()</code> function for working with our nodes and edges as if they were standard “tibbles,” or <a href="https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html">tidy data</a> tables.</p>
<p>Let’s use the <code>activate()</code> function to single out the node list in our network and use the familiar <code>mutate()</code> and <a href="https://tidygraph.data-imaginist.com/reference/group_graph.html"><code>group_components()</code></a> functions to create a new <code>strong_component</code> variable that indicates and saves the strong components to which each node belongs:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="ot">&lt;-</span> dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">strong_component =</span> <span class="fu">group_components</span>(<span class="at">type =</span> <span class="st">"strong"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a look at the nodes in our new <code>dlt1_network</code>, which should now contain our new variable. To do so, we’ll use another handy function from the {tidygraph} package, <code>as_tibble()</code>, that will temporarily convert our node list to a standard table that will allow us to view every row in our node list:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as_tibble</span>(dlt1_network)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 445 × 14
   uid   facilitator role1 experience experience2 grades location region country
   &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  
 1 1     0           libm…          1 6 to 10     secon… VA       South  US     
 2 2     0           clas…          1 6 to 10     secon… FL       South  US     
 3 3     0           dist…          2 11 to 20    gener… PA       North… US     
 4 4     0           clas…          2 11 to 20    middle NC       South  US     
 5 5     0           othe…          3 20+         gener… AL       South  US     
 6 6     0           clas…          1 4 to 5      gener… AL       South  US     
 7 7     0           inst…          2 11 to 20    gener… SD       Midwe… US     
 8 8     0           spec…          1 6 to 10     secon… BE       Inter… BE     
 9 9     0           clas…          1 6 to 10     middle NC       South  US     
10 10    0           scho…          2 11 to 20    middle NC       South  US     
# … with 435 more rows, and 5 more variables: group &lt;chr&gt;, gender &lt;chr&gt;,
#   expert &lt;chr&gt;, connect &lt;chr&gt;, strong_component &lt;int&gt;</code></pre>
</div>
</div>
<p>We could even extend this if we liked to create some standard table summaries using the <code>summarise()</code> function. Run the code below to create a count of the number of nodes in each strong component:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(strong_component) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 209 × 2
   strong_component count
              &lt;int&gt; &lt;int&gt;
 1                1   237
 2                2     1
 3                3     1
 4                4     1
 5                5     1
 6                6     1
 7                7     1
 8                8     1
 9                9     1
10               10     1
# … with 199 more rows</code></pre>
</div>
</div>
<p>Similar to our graph of weak components, we see this network has a strong component with many members (n=237), and the remaining components are all isolated nodes.</p>
<p>If we wanted to illustrate this with a sociogram, we could create a new edge variable using the same <code>activate()</code> and <code>mutate()</code> functions and <code>filter()</code> our edges so our graph only contains reciprocated ties, like so:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(edges) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">reciprocated =</span> <span class="fu">edge_is_mutual</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(reciprocated <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autograph</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="unit-3-case-study-key_files/figure-html/filter_reciprocated-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Or we could filter out all isolates in our strong component network entirely using the same <code>activate()</code> and <code>filter()</code> functions:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(strong_component <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autograph</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="unit-3-case-study-key_files/figure-html/filter_component-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Obviously, this graph would need some polishing before sharing with others, but you get the point. The <code>activate()</code> function from the {tidygraph} package is a powerful tool that let’s you leverage the entire suite of {tidyverse} packages to analyze nodes and edges in a network! We’ll be using the activate function again in section <a href="#b.-egocentric-analysis-size-centrality">3b. Egocentric Analysis: Size &amp; Centrality</a> to calculate node-level measures.</p>
</section>
<section id="cliques" class="level4">
<h4 class="anchored" data-anchor-id="cliques">Cliques</h4>
<p>Whereas top-down approaches to group analysis focus on the complete network and considers parts of it that distinct from the rest of the network, the bottom-up approach focuses is built up from simple dyads and triads that extend into dense clusters that give the network its “clumpiness.” Similar to complete network measures, there are several important properties for which precise definitions and algorithms have been developed, including cliques, clans, plexes, and cores <span class="citation" data-cites="carolan2014">(<a href="#ref-carolan2014" role="doc-biblioref">Carolan 2014</a>)</span>.</p>
<p>Examining cliques is one bottom-up approach that reveals how groups are distributed in the network and which actors belong to which groups.</p>
<blockquote class="blockquote">
<p>A <strong>clique</strong> is a maximally connected subgraph of nodes (&gt; 2) in which all nodes are connected to each other.</p>
</blockquote>
<p>Similar to our component analysis, the {igraph} function has a simple <code>clique_num()</code> function for identifying number of completely connected subgroups in a network:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clique_num</span>(dlt1_network)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>As you probably saw above, the <code>clique_num()</code> function does not take into account directionality of our ties. It looks like we have 8 dense clusters of nodes that all have ties to one another.</p>
<p>The {igraph} function also has a simple <code>cliques()</code> function for identifying members who belong to the same group. In addition to specifying the network you want to examine, this function also allows you to set the minimum and maximum number of members to included in a clique.</p>
<p>Let’s see if there are any cliques that contain a minimum of 8 nodes?</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cliques</span>(dlt1_network, <span class="at">min =</span> <span class="dv">8</span>, <span class="at">max =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[[1]]
+ 8/445 vertices, from faa59c8:
[1]  11  19  24  30  44  60 444 445</code></pre>
</div>
</div>
<p>Unfortunately, the {tidygraph} package does not have a clustering function for cliques. It does, however, include a range popular clustering functions provided that use range of functions that group nodes and edges based on “community structure.” Some of these <a href="https://tidygraph.data-imaginist.com/reference/group_graph.html">community detection algorithms</a> are designed for directed graphs (e.g.&nbsp;our strong component analysis above), while others are for undirected graphs.</p>
<p>One function similar to our clique analysis above is the <code>group_edge_betweenness()</code> function, which group densely connected nodes together. The betweenness centrality measures is something we will look at more closely in the next section.</p>
<p>Because this function can only be used with undirected networks, we will need to pipe <code>|&gt;</code> our <code>dlt_network</code> through the following functions in sequence:</p>
<ol type="1">
<li><strong><code>morph()</code></strong> with the <code>to_undirected</code> argument will temporarily change our directed network to an undirected network, or “symmetrize” our network as discussed in Carolan <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>;</li>
<li><strong><code>activate()</code></strong> will select just our <code>nodes</code> list;</li>
<li><strong><code>mutate()</code></strong> will created a new <code>subgroup</code> variable using the <code>group_edgebetweenness()</code> function;</li>
<li><strong><code>unmorph()</code></strong> will change our undirected network back to a directed network.</li>
</ol>
<p>Run the following code to group our nodes based on their edge betweenness and print our updated <code>dlt1_network</code> object and take a quick look. Because this is a bit computationally intensive, it make take a minute or so to run.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="ot">&lt;-</span> dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">morph</span>(to_undirected) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sub_group =</span> <span class="fu">group_edge_betweenness</span>()) <span class="sc">|&gt;</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unmorph</span>()</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 445 × 15
   uid   facilitator role1 experience experience2 grades location region country
   &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  
 1 1     0           libm…          1 6 to 10     secon… VA       South  US     
 2 2     0           clas…          1 6 to 10     secon… FL       South  US     
 3 3     0           dist…          2 11 to 20    gener… PA       North… US     
 4 4     0           clas…          2 11 to 20    middle NC       South  US     
 5 5     0           othe…          3 20+         gener… AL       South  US     
 6 6     0           clas…          1 4 to 5      gener… AL       South  US     
 7 7     0           inst…          2 11 to 20    gener… SD       Midwe… US     
 8 8     0           spec…          1 6 to 10     secon… BE       Inter… BE     
 9 9     0           clas…          1 6 to 10     middle NC       South  US     
10 10    0           scho…          2 11 to 20    middle NC       South  US     
# … with 435 more rows, and 6 more variables: group &lt;chr&gt;, gender &lt;chr&gt;,
#   expert &lt;chr&gt;, connect &lt;chr&gt;, strong_component &lt;int&gt;, sub_group &lt;int&gt;</code></pre>
</div>
</div>
<p>As you scroll through the nodes tibble produced, you should now see at the far end a new <code>subgroup</code> variable that includes an ID number indicating to which densely connected cluster each node belongs.</p>
<p>Finally, let get a count of Run the following code to group our nodes and print our new&nbsp;<code>cccss_network_groups</code>&nbsp;object and take a quick look:</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sub_group) <span class="sc">|&gt;</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 326 × 2
   sub_group count
       &lt;int&gt; &lt;int&gt;
 1         1    72
 2         2     6
 3         3     5
 4         4     4
 5         5     3
 6         6     3
 7         7     3
 8         8     3
 9         9     2
10        10     2
# … with 316 more rows</code></pre>
</div>
</div>
<p>This out is very telling and suggestive that our network may have a typical <strong>core-periphery structure</strong>: a group of well-connected actors at the center of the network with a set of actors residing on the periphery whose only connections are typically to those actors affiliated with this core group. At the core of our network might reside these actors in subgroup 1, with the remaining actors residing on the periphery.</p>
<p>Note, that if we had wanted to permanently convert our network to an undirected network, we could use the <code>to_undirected</code> argument as a stand-alone function.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>dlt1_undirected <span class="ot">&lt;-</span>  <span class="fu">to_undirected</span>(dlt1_network)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>dlt1_undirected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tbl_graph: 445 nodes and 2529 edges
#
# An undirected multigraph with 4 components
#
# Node Data: 445 × 15 (active)
  uid   facilitator role1 experience experience2 grades location region country
  &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  
1 1     0           libm…          1 6 to 10     secon… VA       South  US     
2 2     0           clas…          1 6 to 10     secon… FL       South  US     
3 3     0           dist…          2 11 to 20    gener… PA       North… US     
4 4     0           clas…          2 11 to 20    middle NC       South  US     
5 5     0           othe…          3 20+         gener… AL       South  US     
6 6     0           clas…          1 4 to 5      gener… AL       South  US     
# … with 439 more rows, and 6 more variables: group &lt;chr&gt;, gender &lt;chr&gt;,
#   expert &lt;chr&gt;, connect &lt;chr&gt;, strong_component &lt;int&gt;, sub_group &lt;int&gt;
#
# Edge Data: 2,529 × 9
   from    to timestamp discussion_title discussion_cate… parent_category
  &lt;int&gt; &lt;int&gt; &lt;chr&gt;     &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;          
1   360   444 4/4/13 1… Most important … Group N          Units 1-3 Disc…
2   356   444 4/4/13 1… Most important … Group D-L        Units 1-3 Disc…
3   356   444 4/4/13 1… DLT Resources—C… Group D-L        Units 1-3 Disc…
# … with 2,526 more rows, and 3 more variables: discussion_identifier &lt;chr&gt;,
#   comment_id &lt;chr&gt;, discussion_id &lt;chr&gt;</code></pre>
</div>
</div>
<p>The {tidygraph} package has a wide range of <a href="https://tidygraph.data-imaginist.com/reference/morphers.html">functions to generate alternate representations of graphs</a>. They can be used as stand alone functions to permanently alter your network, or as an argument with the <code>morph()</code> function to temporarily change your network depending on the analyses you need to perform.</p>
</section>
<section id="your-turn-6" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-6"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>We’ve only scratched the surface of the range of top-down and bottom-up group analysis functions available in the {igraph} and {tidygraph} packages. In the code chunk below, try out one of the other grouping functions available in the <a href="https://tidygraph.data-imaginist.com/reference/group_graph.html">tidygraph</a> or <a href="https://igraph.org/r/html/latest/">igraph</a> packages to examine groups withing the <code>dlt1_network</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOUR CODE HERE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="b.-egocentric-analysis-size-centrality" class="level3">
<h3 class="anchored" data-anchor-id="b.-egocentric-analysis-size-centrality">3b. Egocentric Analysis: Size &amp; Centrality</h3>
<p>In this section, we shift out analytical lens from groups to egos and the pattern of relations in which each individual is embedded. Implicit in egocentric analysis, and also very intuitive to understand, is that:</p>
<blockquote class="blockquote">
<p>An individual’s (<strong>ego</strong>) connections with others (<strong>alters</strong>) provides access to some instrumental (e.g., advice) or expressive (e.g., support) resource that may, in turn, be beneficial.</p>
</blockquote>
<p>As summarized by Carolan <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span>, the structure and content of these relations between an ego and a set of alters is the focus of egocentric network analysis. Since our research question aims to identify “key actors” in our network, we will look at two characteristics of an ego’s connections that are indicative their importance: size and centrality.</p>
<section id="size" class="level4">
<h4 class="anchored" data-anchor-id="size">Size</h4>
<p>Recall from our previous case study focused on complete network analysis, one simple and often ignored structural property of a social network is its size. This also applies to egocentric analysis.</p>
<blockquote class="blockquote">
<p><strong>Size</strong> is simply the number of alters that are directly connected to ego.</p>
</blockquote>
<p>This characteristic is also sometimes referred to as an ego’s <strong>local neighborhood</strong>, and as Carolan points out, size matters, because it indicates the amount of potential resources available in one’s network. For example, a student with a small friendship network may be at a disadvantage when it comes seeking support on schoolwork or advice on course or college enrollment.</p>
<p>We can use the same {tidygraph} process that we used for identifying groups and individual membership to calculate the size for each node. Specifically, we will need to <code>activate()</code> the <code>nodes</code> in our network and create a new variable which we’ll call <code>size</code> that is calculated using the <code>local_size()</code> function.</p>
<p>And since it’s much easier to inspect our data as a tibble than using the graph output, we’ll also convert our node to a table and <code>arrange()</code> in descending order by <code>size</code> to make it easier to see the range in values of our network:</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="ot">&lt;-</span> dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">size =</span> <span class="fu">local_size</span>())</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span> </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(size)) <span class="sc">|&gt;</span> </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(uid, facilitator, size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 445 × 3
   uid   facilitator  size
   &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;
 1 444   1             295
 2 445   1             160
 3 44    0              61
 4 11    0              51
 5 7     0              42
 6 30    0              42
 7 19    0              39
 8 60    0              39
 9 36    0              37
10 432   0              36
# … with 435 more rows</code></pre>
</div>
</div>
<p>Not surprisingly, the egos with the most alters are the course facilitators who played a very active role in this course and therefore have an outsize influence on the structure of this network.</p>
<p><strong>Note:</strong> In the code immediately above or earlier in this case study, it’s important to take note when we have permanently altered our <code>dlt1_network</code> object and when we have only made temporary changes to our network. For example, when creating a new variable for local neighborhood size, we assigned the changes made to <code>dlt1_network</code> to an object of the same name using the <code>&lt;-</code> assignment operator. This effectively overwrites the old object with the new object because was wanted to save the new variable created. However, when converting network to a tibble consisting of nodes and their <code>facilitor</code> and <code>size</code> attributes, we did not assign to <code>dlt1_network</code> because we did not want to permanently change to our network object to a tibble.</p>
</section>
<section id="centrality" class="level4">
<h4 class="anchored" data-anchor-id="centrality">Centrality</h4>
<p>As we learned in our previous case study and readings, a key structural property of networks is the concept of centralization. A network that is highly centralized is one in which relations are focused on a small number of actors or even a single actor in a network, whereas ties in a decentralized network are diffuse and spread over a number of actors. As we saw above, the facilitators in our network play an outsize role in the MOOC-Ed discussions!</p>
<p><strong>Degree</strong></p>
<p>One of the most common descriptives reported in network studies and a primary measure of centralization is degree.</p>
<blockquote class="blockquote">
<p><strong>Degree</strong> is the number of ties to and from an ego. In a directed network, in-degree is the number of ties received, whereas out-degree is the number of ties sent.</p>
</blockquote>
<p>The {tidygraph} package has an aptly named function <code>centrality_degree()</code> for calculating degree, in-degree, and out-degree for all actors in a network.</p>
<p>Run the following create two new variables for our nodes: <code>in_dgree</code> and <code>out_degree</code>. We’ll set the <code>mode =</code> argument in <code>centrality_degree()</code> function to <code>"in"</code> and <code>"out"</code> respectively.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="ot">&lt;-</span> dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">in_degree =</span> <span class="fu">centrality_degree</span>(<span class="at">mode =</span> <span class="st">"in"</span>),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">out_degree =</span> <span class="fu">centrality_degree</span>(<span class="at">mode =</span> <span class="st">"out"</span>))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span> </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 445 × 18
   uid   facilitator role1 experience experience2 grades location region country
   &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  
 1 1     0           libm…          1 6 to 10     secon… VA       South  US     
 2 2     0           clas…          1 6 to 10     secon… FL       South  US     
 3 3     0           dist…          2 11 to 20    gener… PA       North… US     
 4 4     0           clas…          2 11 to 20    middle NC       South  US     
 5 5     0           othe…          3 20+         gener… AL       South  US     
 6 6     0           clas…          1 4 to 5      gener… AL       South  US     
 7 7     0           inst…          2 11 to 20    gener… SD       Midwe… US     
 8 8     0           spec…          1 6 to 10     secon… BE       Inter… BE     
 9 9     0           clas…          1 6 to 10     middle NC       South  US     
10 10    0           scho…          2 11 to 20    middle NC       South  US     
# … with 435 more rows, and 9 more variables: group &lt;chr&gt;, gender &lt;chr&gt;,
#   expert &lt;chr&gt;, connect &lt;chr&gt;, strong_component &lt;int&gt;, sub_group &lt;int&gt;,
#   size &lt;dbl&gt;, in_degree &lt;dbl&gt;, out_degree &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>A Quick Note about Multigraphs and Tie Strength</strong></p>
<p>You may have noticed in this network that indegree exceeds the total number of nodes in our network are are wondering how that is possible. Recall that our network is currently treated at a “multigraph,” indicating that some dyads have multiple edges. Therefore, some edges between dyads are counted more than once.</p>
<p>Alternatively, we could “<a href="https://igraph.org/r/doc/simplify.html">simplify</a>” our network by collapsing multiple edges between the same actors and assigning a value to edges between actors indicating tie strength. In this case it would be a measure of frequency of replies between actors. However, in the process of simplifying our network, we would lose important contextual information about the context of each tie, such as the when (timestamp) and where (forum) each tie was created.</p>
<p>Let’s dust off our <a href="https://ggplot2-book.org/getting-started.html#basic-use"><code>ggplot()</code></a> skills and take a look at the distribution of <code>out_degree</code>, or the number of replies to other posts, by using in <code>geom_histogram()</code> function for creating histograms.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> out_degree))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="unit-3-case-study-key_files/figure-html/geom_histogram-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that most egos in the network sent very few replies to alters in the course, while a handful of actors in this network have sent 30 or more replies.</p>
<p><strong>Compositional and Variance Measures</strong></p>
<p>Carolan <span class="citation" data-cites="carolan2014">Carolan (<a href="#ref-carolan2014" role="doc-biblioref">2014</a>)</span> notes that there are two types of measures that can emerge from egocentric data: compositional and variance. Compositional measures are those created by counting or taking the average of egocentric network variables. Variance measures, on the other hand, are simply those that are derived by calculating the variance or standard deviation of the egocentric network variables.</p>
<p>While we could calculate invdividually the mean and variance for each egocentric measure created above using the <code>summarise()</code> function demonstrated earlier, R has a package and function to save us the effort.</p>
<p>To quickly calculate summary statistics for our nodes, including compositional and variance measures for our egocentric measures, we can use the <code>skim()</code> function from the {skimr} package to take a quick look at the variables in our node list:</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">as_tibble(dlt1_network)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">445</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">uid</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">445</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">facilitator</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">role1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">experience2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">grades</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">location</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">region</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">country</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">group</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">expert</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">connect</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">experience</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">▆▁▇▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">strong_component</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">49.84</td>
<td style="text-align: right;">66.43</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">209</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sub_group</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">121.55</td>
<td style="text-align: right;">106.59</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">215</td>
<td style="text-align: right;">326</td>
<td style="text-align: left;">▇▃▃▃▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">size</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8.75</td>
<td style="text-align: right;">17.51</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">295</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">in_degree</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.68</td>
<td style="text-align: right;">26.74</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">475</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">out_degree</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.68</td>
<td style="text-align: right;">9.84</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">106</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can see, for example, that egos in our network are connected with on average 8.75 alters with a standards deviation of 17.5. Notice also that our mean for in-degree and out-degree are identical. This will always be the case since for every tie that goes “in” there is always one going “out.”</p>
<p>Finally, the {skimr} package like our {tidgraph} package plays nicely with other {tidyverse} packages for data wrangling and analysis. For example, let’s select only MOOC-Ed participants who are located in the United States and calculate compositional and variance measures for <code>size</code> by educator’s role:</p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">"US"</span>) <span class="sc">|&gt;</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(role1) <span class="sc">|&gt;</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(size) <span class="sc">|&gt;</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">select(…)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">412</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">role1</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 2%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: left;">role1</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">size</td>
<td style="text-align: left;">classteaching</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8.97</td>
<td style="text-align: right;">8.22</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">39</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">size</td>
<td style="text-align: left;">curriculum</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.70</td>
<td style="text-align: right;">7.22</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">8.50</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">size</td>
<td style="text-align: left;">districtadmin</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.50</td>
<td style="text-align: right;">4.74</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">size</td>
<td style="text-align: left;">instructionaltech</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.46</td>
<td style="text-align: right;">9.38</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: right;">61</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">size</td>
<td style="text-align: left;">libmedia</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.91</td>
<td style="text-align: right;">9.91</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">33</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">size</td>
<td style="text-align: left;">Operations</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">▁▁▇▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">size</td>
<td style="text-align: left;">other</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8.25</td>
<td style="text-align: right;">8.10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">12.25</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">▇▁▃▁▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">size</td>
<td style="text-align: left;">otheredprof</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">18.95</td>
<td style="text-align: right;">53.48</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">295</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">size</td>
<td style="text-align: left;">profdev</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.71</td>
<td style="text-align: right;">4.44</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">7.50</td>
<td style="text-align: right;">21</td>
<td style="text-align: left;">▇▂▂▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">size</td>
<td style="text-align: left;">schooladmin</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.40</td>
<td style="text-align: right;">9.10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3.25</td>
<td style="text-align: right;">5.5</td>
<td style="text-align: right;">13.50</td>
<td style="text-align: right;">42</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">size</td>
<td style="text-align: left;">specialed</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">6.63</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">11.00</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">17.00</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">▃▁▇▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">size</td>
<td style="text-align: left;">techinfrastructure</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.44</td>
<td style="text-align: right;">3.22</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">▇▂▃▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As illustrated by the output above, we can see that “otheredprof” (i.e., other educational professionals including our facilitators) were connected with the most individuals on average (18.9), while educators in “Operations” connected with the fewest individuals on average (3).</p>
<p><strong>Closeness &amp; Betweenness</strong></p>
<p>Two other centrality measures for identifying key actors in a network are closeness and betweenness. Whereas degree centrality is a local measure and can be calculated without needing information about the overall pattern of relations among ego and alters, closeness and betweenness address this shortcoming by taking into account indirect ties among all the alters in an ego’s network.</p>
<p><strong>Closeness</strong> centrality captures the average distance an actor is from all other actors in the network and is a function of an actor’s geodesic distance to others, which equals the length of shortest path connecting a pair of actors. It’s an intuitively appealing measure in that being “close” to others may provide an advantage by giving you early access to new information or by indicating how quickly an actor can exchange something with others (Knoke &amp; Yang, 2008).</p>
<p><strong>Betweenness</strong> centrality measures the degree to which other actors lie on the shortest geodesic path between pairs of actors in the network. Betweenness may be indicative of how actors control or mediate the relations between pairs of actors that are not directly connected. Therefore, this measure is an important indicator of control over information exchange or resource flows within a network (Knoke &amp; Yang, 2008). The more any given actor is located on the path between numerous dyads, the higher that actor’s potential to control network interactions. This concept and its associated measure is very appealing, as it captures the degree to which an actor occupies a strategically important position.</p>
</section>
<section id="your-turn-7" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-7"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Use the code chunk below to add a <code>closeness</code> and <code>betweenness</code> variable to the nodes in our network and answer the questions that follow. <strong>Hint</strong>: you may want to look at the <a href="https://tidygraph.data-imaginist.com/reference/centrality.html">functions to calculate node and edge centrality</a> on the {tidygraph} package website.</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOUR CODE HERE</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="ot">&lt;-</span> dlt1_network <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(nodes) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">closeness =</span> <span class="fu">centrality_closeness</span>(),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">betweenness =</span> <span class="fu">centrality_betweenness</span>()) <span class="sc">|&gt;</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(betweenness))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>dlt1_network <span class="sc">|&gt;</span> </span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 445 × 20
   uid   facilitator role1 experience experience2 grades location region country
   &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  
 1 444   1           othe…          3 20+         gener… NC       South  US     
 2 445   1           othe…          3 20+         gener… NC       South  US     
 3 44    0           inst…          2 11 to 20    middle NC       South  US     
 4 19    0           othe…          3 20+         colle… AU       Inter… AU     
 5 30    0           scho…          3 20+         secon… NC       South  US     
 6 432   0           inst…          1 6 to 10     secon… NC       South  US     
 7 60    0           clas…          2 11 to 20    middle NC       South  US     
 8 11    0           other          3 20+         gener… KG       Inter… KG     
 9 109   0           inst…          3 20+         prima… TX       South  US     
10 36    0           clas…          2 11 to 20    secon… UT       West   US     
# … with 435 more rows, and 11 more variables: group &lt;chr&gt;, gender &lt;chr&gt;,
#   expert &lt;chr&gt;, connect &lt;chr&gt;, strong_component &lt;int&gt;, sub_group &lt;int&gt;,
#   size &lt;dbl&gt;, in_degree &lt;dbl&gt;, out_degree &lt;dbl&gt;, closeness &lt;dbl&gt;,
#   betweenness &lt;dbl&gt;</code></pre>
</div>
</div>
<ol type="1">
<li><p>Which two actors have the highest betweenness and what is unique about their role in the course?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>Do these same two actors also have the highest closeness? How might you interpret that?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
<p>Again, we’ve only scratched the surface of the vast number of centrality meaures available in the {igraph} and {tidygraph} packages. Feel free to explore <a href="https://tidygraph.data-imaginist.com/reference/centrality.html">other functions to calculate node and edge centrality</a> in these two packages.</p>
</section>
</section>
</section>
<section id="model" class="level2">
<h2 class="anchored" data-anchor-id="model">4. MODEL</h2>
<p>As highlighted in&nbsp;<a href="https://datascienceineducation.com/c03.html">Chapter 3 of Data Science in Education Using R</a>, the&nbsp;<strong>Model</strong>&nbsp;step of the data science process entails “using statistical models, from simple to complex, to understand trends and patterns in the data.” The authors note that while descriptive statistics and data visualization during the&nbsp;<strong>Explore</strong> step can help us to identify patterns and relationships in our data, statistical models can be used to help us determine if relationships, patterns and trends are actually meaningful.</p>
<p>We will not explore the use of models for SNA until Unit 3, but recall from <a href="#a-social-network-perspective-in-mooc-eds">A Social Network Perspective in MOOC-Eds</a> was guided by the following questions:</p>
<ol type="1">
<li><p>What are the patterns of peer interaction and the structure of peer networks that emerge over the course of a MOOC-Ed?</p></li>
<li><p>To what extent do participant and network attributes (e.g., homophily, reciprocity, transitivity) account for the structure of these networks?</p></li>
<li><p>To what extent do these networks result in the co-construction of new knowledge?</p></li>
</ol>
<p>To address Question 1, actors in the network were categorized into distinct mutually exclusive groups using the core-periphery and regular equivalence functions of UCINET. The former used the CORR algorithm to divide the network into actors that are part of a densely connected subgroup, or “core”, from those that are part of the sparsely connected periphery. Regular equivalence employs the REGE blockmodeling algorithm to partition, or group, actors in the network based on the similarity of their ties to others with similar ties. In essence, blockmodeling provides a systematic way for categorizing educators based on the ways in which they interacted with peers.</p>
<p>As we saw upon just a basic visual inspection of our network during the Explore section, there was a small core of highly connected participants surrounded by those on the “periphery,” or edge, of the network with very few connections. In the DLT 2 course, those on the periphery made up roughly 90% of network! The study also found relatively high levels of reciprocation, but also found that roughly a quarter of participants were characterized as “brodcasters” – educators who initiated a discussion thread, but neither reciprocated with those who replied, nor posted to threads initiated by others.</p>
<p><img src="img/positions.jpeg" class="img-fluid" style="width:80.0%"></p>
<p>To address Question 2, this study use the exponential family of random graph models (ERGM; also known as p* models), which provide a statistical approach to network modeling that addresses the complex dependencies within networks. ERGMs predict network ties and determine the statistical likelihood of a given network structure, based on an assumed dependency structure, the attributes of the individuals (e.g., gender, popularity, location, previous ties) and prior states of the network.</p>
<section id="your-turn-8" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-8"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Recall that network analyses to identify groups, positions, and central actors are a means to an end rather than an end in itself <span class="citation" data-cites="carolan2014">(<a href="#ref-carolan2014" role="doc-biblioref">Carolan 2014</a>)</span>. One primary goal of gathering data about a network’s groups, positions, and central actors – a goal which we’ll explore more deeply in later units – is test whether there is a relationship between these measures and educational outcomes of interest. That was ultimately the aim of the research article guiding this study, but sadly got neglected.</p>
<p>Thinking about the node and group level analyses we’ve conducted so far, and what you know about this educational context so far, write a research question or hypothesis you would like to test that would examine whether there is a relationship between these group or node-level measures and educational outcomes appropriate for this MOOC-Ed.</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul>
<hr>
</section>
</section>
<section id="communicate" class="level2">
<h2 class="anchored" data-anchor-id="communicate">5. COMMUNICATE</h2>
<p>For your final Your Turn, your goal is to distill our analysis from above into a simple “data product” designed to illustrate key findings about changes in the collaboration network over time. For the purposes of this task, imagine that your audience consists of the developers and facilitators of the DLT MOOC-Eds who have limited background in SNA and adapt the following steps accordingly:</p>
<ol type="1">
<li><p><strong>Select.</strong> Select a group and/or node-level analysis from above, or a new analysis if so motivated, that you think would be interesting or relevant for the target audience and that helps answer our research questions.</p></li>
<li><p><strong>Polish.</strong> Create and polish a data visualization and/or data table to communicate your selected findings.</p></li>
<li><p><strong>Narrate.</strong> Write a brief narrative (2-3 paragraphs) to accompany your visualization and/or table that includes the following:</p>
<ul>
<li><p>The question or questions guiding the analysis;</p></li>
<li><p>The conclusions you’ve reached based on our findings;</p></li>
<li><p>How your audience might use this information;</p></li>
<li><p>How you might revisit or improve upon this analysis in the future.</p></li>
</ul></li>
</ol>
<section id="your-turn-9" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-9"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Use the code chunk below create a polished table and/or visualization(s) and write a brief narrative in the space that follows.</p>
</section>
<section id="data-visualization-or-table" class="level3">
<h3 class="anchored" data-anchor-id="data-visualization-or-table">Data Visualization or Table</h3>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOUR CODE HERE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="narrative" class="level3">
<h3 class="anchored" data-anchor-id="narrative">Narrative</h3>
<p>NARRATIVE GOES HERE…</p>
</section>
<section id="knit-check" class="level3">
<h3 class="anchored" data-anchor-id="knit-check">🧶 Knit &amp; Check ✅</h3>
<p>Congratulations - you’ve completed the Unit 3 case study! To share your work, click the drop down arrow next to the ball of yarn that says “Knit” at the top of this markdown file, then select “Knit top HTML”. Assuming your code contains no errors, this will create a web page in your Files pane that serves as a record of your work.</p>
<p>Once your file has been knitted, you can publish this file online using RPubs, or share the HTML file through another means.</p>
</section>
<section id="references" class="level3">



</section>
</section>
<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-carolan2014" class="csl-entry" role="doc-biblioentry">
Carolan, Brian. 2014. <span>“Social Network Analysis and Education: Theory, Methods &amp; Applications.”</span> <a href="https://doi.org/10.4135/9781452270104">https://doi.org/10.4135/9781452270104</a>.
</div>
<div id="ref-kellogg2015massively" class="csl-entry" role="doc-biblioentry">
Kellogg, Shaun, and Achim Edelmann. 2015. <span>“Massively Open Online Course for Educators (MOOC-e d) Network Dataset.”</span> <em>British Journal of Educational Technology</em> 46 (5): 977–83.
</div>
<div id="ref-krumm2018" class="csl-entry" role="doc-biblioentry">
Krumm, Andrew, Barbara Means, and Marie Bienkowski. 2018. <em>Learning Analytics Goes to School</em>. Routledge. <a href="https://doi.org/10.4324/9781315650722">https://doi.org/10.4324/9781315650722</a>.
</div>
<div id="ref-wickham2016r" class="csl-entry" role="doc-biblioentry">
Wickham, Hadley, and Garrett Grolemund. 2016. <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data</em>. " O’Reilly Media, Inc.". <a href="https://r4ds.had.co.nz">https://r4ds.had.co.nz</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    setTimeout(function() {
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->


</body></html>